name: Bug Report
description: Report a bug in dargstack
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: input
    attributes:
      label: dargstack version
      description: Output of `dargstack --version`
    validations:
      required: true
  - type: input
    attributes:
      label: Docker version
      description: Output of `docker --version`
  - type: dropdown
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
