name: Feature Request
description: Suggest a feature for dargstack
type: feature
body:
  - type: textarea
    attributes:
      label: Description
      description: What feature would you like?
    validations:
      required: true
